# Generated by Django 5.2.6 on 2026-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tower_id", models.CharField(max_length=2, verbose_name="城池ID")),
                (
                    "tower_name",
                    models.CharField(max_length=20, verbose_name="城池名称"),
                ),
                (
                    "session_id",
                    models.CharField(max_length=20, unique=True, verbose_name="会话ID"),
                ),
                (
                    "left_time",
                    models.IntegerField(default=0, verbose_name="剩余时间(秒)"),
                ),
                (
                    "attack_time",
                    models.DateTimeField(db_index=True, verbose_name="攻击时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "攻击记录",
                "verbose_name_plural": "攻击记录",
                "ordering": ["-attack_time"],
            },
        ),
    ]
