# Generated by Django 5.2.6 on 2026-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tower", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attackrecord",
            name="session_id",
            field=models.CharField(max_length=20, verbose_name="会话ID"),
        ),
    ]
