# Generated by Django 5.2.6 on 2026-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tower", "0002_alter_attackrecord_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attackrecord",
            name="predicted_cities",
            field=models.CharField(
                blank=True,
                help_text="本轮攻击前预测的3个城市，逗号分隔",
                max_length=60,
                null=True,
                verbose_name="预测城市",
            ),
        ),
        migrations.AddField(
            model_name="attackrecord",
            name="prediction_correct",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="预测是否正确"
            ),
        ),
    ]
